name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install packages
      run: |
        pip install pylint
        pip install pyqt5
        pip install pyqt5-tools
        pip install pillow
        pip install sounddevice
        pip install moviepy
        pip install cv2
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
