name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install pylint -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install pyqt5 -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install pyqt5-tools -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install sounddevice -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install moviepy -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install pyaudio -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip install pillow -i https://pypi.tuna.tsinghua.edu.cn/simple
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
